name: Deploy

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/deploy.yml
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    defaults:
      run:
        working-directory: website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo ::set-output name=version::$(cat .nvmrc)
        id: nvm
      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ steps.nvm.outputs.version }}
          registry-url: https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }} # Engineering user PAT
      - name: Initialize cache
        id: yarn-cache-dir
        run: echo ::set-output name=dir::$(yarn cache dir)
      - name: Restore cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }} # Engineering user PAT
      - name: Build
        run: echo "Building ..."
      - name: Deploy
        run: echo "Deploying ..."
