name: Validate

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo ::set-output name=version::$(cat .nvmrc)
        id: nvm
      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ steps.nvm.outputs.version }}
          registry-url: https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }} # Engineering user PAT
      - name: Initialize cache
        id: yarn-cache-dir
        run: echo ::set-output name=dir::$(yarn cache dir)
      - name: Restore cache
        uses: actions/cache@v2.1.4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-scripts --prefer-offline
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }} # Engineering user PAT
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
